version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - ./web:/usr/src/app
      - django_static_dev:/usr/src/app/static
    env_file: .env
    environment:
      DJANGOs_DEBUG: "True"
    command: ./post-production-deploy.sh

  nginx:
    restart: always
    build: ./nginx/
    hostname: "nginx"
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  django_static_dev:
  postgres_data_dev: